main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('tambah_kegiatan/', views.tambah_kegiatan, name='tambah_kegiatan'),
    path('tambah_orang/<int:id>/', views.tambah_orang, name='tambah_orang'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.forms import ModelForm

class Kegiatan (models.Model):
    nama_kegiatan = models.CharField(max_length = 50)
    deskripsi_kegiatan = models.TextField("deskripsi")
    def __str__(self):
        return (self.nama_kegiatan)

class Person (models.Model):
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, default=0)
    person_name = models.CharField("nama lengkap",max_length = 50)
    def __str__(self):
        return self.person_name
class Form_Kegiatan (ModelForm):
    class Meta:
        model = Kegiatan
        fields = "__all__"
class Form_Person (ModelForm):
    class Meta:
        model = Person
        fields = ["person_name"]
# Create your models here.

main/views.py
from django.shortcuts import render,redirect
from .models import Kegiatan,Person, Form_Kegiatan, Form_Person

def home(request):
    persons = Person.objects.all()
    kegiatans = Kegiatan.objects.all()
    return render(request, 'kegiatan.html', {"person" : persons, "kegiatan" : kegiatans})

def tambah_kegiatan(request):
    if (request.method == "POST"):
        form = Form_Kegiatan(request.POST)
        if form.is_valid():
            form.save()
            return redirect("main:home")
    else:
        form = Form_Kegiatan()
        return render(request, "tambah_kegiatan.html",{"form" : form})

def tambah_orang(request, id):
    if (request.method == "POST"):
        form = Form_Person(request.POST)
        if form.is_valid():
            kegiatan = Kegiatan.objects.get(id=id)
            form = Person(kegiatan = kegiatan, person_name= form.data["person_name"])
            form.save()
            return redirect("main:home")
    else:
        form = Form_Person()
        return render(request, "tambah_orang.html",{"form" : form})

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'main:home' %}">Jafar Abdurrohman</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item ml-2">
                    <a class="nav-link" href="{% url 'main:home' %}">Home</a>
                </li>
                <li class="nav-item ml-5">
                    <a class="nav-link" href="{% url 'main:tambah_kegiatan' %}">Tambah Kegiatan</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock content %}
</body>

</html>

templates/kegiatan.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
            {% for data in kegiatan %}
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope='col' colspan="2" class="text-center"><b> {{ data.nama_kegiatan }} </b></th>
                    </tr>
                    <tr>
                        <th scope='col' colspan="2" class="text-center"><b> {{ data.deskripsi_kegiatan }} </b></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        {% for orang in person %}
                            {% if orang.kegiatan == data %}
                                <tr>
                                    <td align="center"> {{ orang.person_name }} </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    <tr>
                    <tr>
                        <td align="center">
                            <a class="btn btn-outline-dark btn-block" href="tambah_orang/{{ data.id }}">Daftar</a>
                        </td>
                    </tr>
                    </tr>
                    </tbody>
                </table>
            {% endfor %}
    </div>
{% endblock %}

templates/tambah_kegiatan.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
    <h2>Tambah Kegiatan</h2>
    <form action="#" method="POST">
        {% csrf_token %}
        <table>
            {{ form|crispy }}
        </table>
        <input class="btn btn-outline-dark btn-block" type="submit" value="submit">
    </form>
    </div>
{% endblock %}

templates/tambah_orang.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
    <form action="#" method="POST">
        {% csrf_token %}
        <table>
            {{ form|crispy }}
        </table>
        <input class="btn btn-outline-dark btn-block" type="submit" value="submit">
    </form>
    </div>
{% endblock %}